name: Hello World

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"

      - name: Checkout repo
        uses: actions/checkout@v4